INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "-", "-", "-");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "AD", "AD", "ANDORRA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "AE", "AE", "UNITED ARAB EMIRATES");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "AF", "AF", "AFGHANISTAN");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "AG", "AG", "ANTIGUA AND BARBUDA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "AI", "AI", "ANGUILLA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "AL", "AL", "ALBANIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "AM", "AM", "ARMENIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "AN", "AN", "NETHERLANDS ANTILLES");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "AO", "AO", "ANGOLA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "AP", "AP", "NON-SPEC ASIA PAS LOCATION");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "AR", "AR", "ARGENTINA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "AS", "AS", "AMERICAN SAMOA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "AT", "AT", "AUSTRIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "AU", "AU", "AUSTRALIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "AW", "AW", "ARUBA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "AX", "AX", "ALAND ISLANDS");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "AZ", "AZ", "AZERBAIJAN");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "BA", "BA", "BOSNIA AND HERZEGOWINA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "BB", "BB", "BARBADOS");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "BD", "BD", "BANGLADESH");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "BE", "BE", "BELGIUM");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "BF", "BF", "BURKINA FASO");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "BG", "BG", "BULGARIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "BH", "BH", "BAHRAIN");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "BI", "BI", "BURUNDI");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "BJ", "BJ", "BENIN");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "BM", "BM", "BERMUDA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "BN", "BN", "BRUNEI DARUSSALAM");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "BO", "BO", "BOLIVIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "BR", "BR", "BRAZIL");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "BS", "BS", "BAHAMAS");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "BT", "BT", "BHUTAN");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "BW", "BW", "BOTSWANA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "BY", "BY", "BELARUS");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "BZ", "BZ", "BELIZE");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "CA", "CA", "CANADA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "CD", "CD", "CONGO THE DEMOCRATIC REPUBLIC OF THE");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "CF", "CF", "CENTRAL AFRICAN REPUBLIC");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "CH", "CH", "SWITZERLAND");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "CI", "CI", "COTE D'IVOIRE");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "CK", "CK", "COOK ISLANDS");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "CL", "CL", "CHILE");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "CM", "CM", "CAMEROON");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "CN", "CN", "CHINA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "CO", "CO", "COLOMBIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "CR", "CR", "COSTA RICA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "CS", "CS", "Serbia and Montenegro (Formally Czechoslovakia)");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "CU", "CU", "CUBA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "CY", "CY", "CYPRUS");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "CZ", "CZ", "CZECH REPUBLIC");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "DE", "DE", "GERMANY");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "DJ", "DJ", "DJIBOUTI");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "DK", "DK", "DENMARK");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "DO", "DO", "DOMINICAN REPUBLIC");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "DZ", "DZ", "ALGERIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "EC", "EC", "ECUADOR");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "EE", "EE", "ESTONIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "EG", "EG", "EGYPT");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "ER", "ER", "ERITREA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "ES", "ES", "SPAIN");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "ET", "ET", "ETHIOPIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "EU", "EU", "EUROPEAN UNION");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "FI", "FI", "FINLAND");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "FJ", "FJ", "FIJI");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "FM", "FM", "MICRONESIA FEDERATED STATES OF");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "FO", "FO", "FAROE ISLANDS");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "FR", "FR", "FRANCE");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "GA", "GA", "GABON");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "UK", "UK", "UNITED KINGDOM");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "GD", "GD", "GRENADA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "GE", "GE", "GEORGIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "GF", "GF", "FRENCH GUIANA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "GH", "GH", "GHANA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "GI", "GI", "GIBRALTAR");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "GL", "GL", "GREENLAND");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "GM", "GM", "GAMBIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "GP", "GP", "GUADELOUPE");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "GR", "GR", "GREECE");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "GT", "GT", "GUATEMALA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "GU", "GU", "GUAM");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "GW", "GW", "GUINEA-BISSAU");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "GY", "GY", "GUYANA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "HK", "HK", "HONG KONG");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "HN", "HN", "HONDURAS");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "HR", "HR", "CROATIA (local name: Hrvatska)");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "HT", "HT", "HAITI");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "HU", "HU", "HUNGARY");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "ID", "ID", "INDONESIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "IE", "IE", "IRELAND");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "IL", "IL", "ISRAEL");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "IN", "IN", "INDIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "IO", "IO", "BRITISH INDIAN OCEAN TERRITORY");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "IQ", "IQ", "IRAQ");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "IR", "IR", "IRAN (ISLAMIC REPUBLIC OF)");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "IS", "IS", "ICELAND");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "IT", "IT", "ITALY");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "JE", "JE", "JERSEY");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "JM", "JM", "JAMAICA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "JO", "JO", "JORDAN");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "JP", "JP", "JAPAN");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "KE", "KE", "KENYA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "KG", "KG", "KYRGYZSTAN");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "KH", "KH", "CAMBODIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "KI", "KI", "KIRIBATI");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "KN", "KN", "SAINT KITTS AND NEVIS");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "KR", "KR", "KOREA REPUBLIC OF");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "KW", "KW", "KUWAIT");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "KY", "KY", "CAYMAN ISLANDS");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "KZ", "KZ", "KAZAKHSTAN");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "LA", "LA", "LAO PEOPLE'S DEMOCRATIC REPUBLIC");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "LB", "LB", "LEBANON");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "LC", "LC", "SAINT LUCIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "LI", "LI", "LIECHTENSTEIN");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "LK", "LK", "SRI LANKA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "LR", "LR", "LIBERIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "LS", "LS", "LESOTHO");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "LT", "LT", "LITHUANIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "LU", "LU", "LUXEMBOURG");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "LV", "LV", "LATVIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "LY", "LY", "LIBYAN ARAB JAMAHIRIYA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "MA", "MA", "MOROCCO");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "MC", "MC", "MONACO");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "MD", "MD", "MOLDOVA REPUBLIC OF");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "MG", "MG", "MADAGASCAR");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "MK", "MK", "MACEDONIA THE FORMER YUGOSLAV REPUBLIC OF");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "ML", "ML", "MALI");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "MM", "MM", "MYANMAR");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "MN", "MN", "MONGOLIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "MO", "MO", "MACAU");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "MP", "MP", "NORTHERN MARIANA ISLANDS");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "MR", "MR", "MAURITANIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "MT", "MT", "MALTA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "MU", "MU", "MAURITIUS");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "MV", "MV", "MALDIVES");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "MW", "MW", "MALAWI");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "MX", "MX", "MEXICO");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "MY", "MY", "MALAYSIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "MZ", "MZ", "MOZAMBIQUE");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "NA", "NA", "NAMIBIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "NC", "NC", "NEW CALEDONIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "NE", "NE", "NIGER");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "NF", "NF", "NORFOLK ISLAND");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "NG", "NG", "NIGERIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "NI", "NI", "NICARAGUA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "NL", "NL", "NETHERLANDS");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "NO", "NO", "NORWAY");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "NP", "NP", "NEPAL");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "NR", "NR", "NAURU");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "NU", "NU", "NIUE");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "NZ", "NZ", "NEW ZEALAND");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "OM", "OM", "OMAN");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "PA", "PA", "PANAMA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "PE", "PE", "PERU");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "PF", "PF", "FRENCH POLYNESIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "PG", "PG", "PAPUA NEW GUINEA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "PH", "PH", "PHILIPPINES");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "PK", "PK", "PAKISTAN");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "PL", "PL", "POLAND");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "PR", "PR", "PUERTO RICO");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "PS", "PS", "PALESTINIAN TERRITORY OCCUPIED");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "PT", "PT", "PORTUGAL");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "PW", "PW", "PALAU");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "PY", "PY", "PARAGUAY");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "QA", "QA", "QATAR");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "RO", "RO", "ROMANIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "RS", "RS", "SERBIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "RU", "RU", "RUSSIAN FEDERATION");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "RW", "RW", "RWANDA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "SA", "SA", "SAUDI ARABIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "SB", "SB", "SOLOMON ISLANDS");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "SC", "SC", "SEYCHELLES");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "SD", "SD", "SUDAN");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "SE", "SE", "SWEDEN");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "SG", "SG", "SINGAPORE");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "SI", "SI", "SLOVENIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "SK", "SK", "SLOVAKIA (Slovak Republic)");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "SL", "SL", "SIERRA LEONE");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "SM", "SM", "SAN MARINO");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "SN", "SN", "SENEGAL");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "SR", "SR", "SURINAME");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "SV", "SV", "EL SALVADOR");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "SY", "SY", "SYRIAN ARAB REPUBLIC");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "SZ", "SZ", "SWAZILAND");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "TG", "TG", "TOGO");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "TH", "TH", "THAILAND");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "TJ", "TJ", "TAJIKISTAN");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "TM", "TM", "TURKMENISTAN");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "TN", "TN", "TUNISIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "TO", "TO", "TONGA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "TR", "TR", "TURKEY");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "TT", "TT", "TRINIDAD AND TOBAGO");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "TV", "TV", "TUVALU");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "TW", "TW", "TAIWAN PROVINCE OF CHINA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "TZ", "TZ", "TANZANIA UNITED REPUBLIC OF");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "UA", "UA", "UKRAINE");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "UG", "UG", "UGANDA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "US", "US", "UNITED STATES");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "UY", "UY", "URUGUAY");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "UZ", "UZ", "UZBEKISTAN");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "VA", "VA", "HOLY SEE (VATICAN CITY STATE)");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "VE", "VE", "VENEZUELA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "VG", "VG", "VIRGIN ISLANDS (BRITISH)");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "VI", "VI", "VIRGIN ISLANDS (U.S.)");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "VN", "VN", "VIET NAM");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "VU", "VU", "VANUATU");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "WS", "WS", "SAMOA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "YE", "YE", "YEMEN");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "YU", "YU", "Serbia and Montenegro (Formally Yugoslavia)");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "ZA", "ZA", "SOUTH AFRICA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "ZM", "ZM", "ZAMBIA");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "ZW", "ZW", "ZIMBABWE");
INSERT INTO kalturadw.dwh_dim_locations(location_type_name, location_name, country, country_name) VALUES("country", "ZZ", "ZZ", "RESERVED");

UPDATE kalturadw.dwh_dim_locations SET country_id = location_id;