USE kalturadw;

DROP TABLE IF EXISTS `dwh_hourly_partner`;

CREATE TABLE `dwh_hourly_partner` (
  `partner_id` int(11) NOT NULL DEFAULT '0',
  `date_id` int(11) NOT NULL DEFAULT '0',
  `hour_id` int(11) NOT NULL DEFAULT '0',
  `sum_time_viewed` decimal(20,3) DEFAULT NULL,
  `count_time_viewed` int(11) DEFAULT NULL,
  `count_plays` int(11) DEFAULT NULL,
  `count_loads` int(11) DEFAULT NULL,
  `count_plays_25` int(11) DEFAULT NULL,
  `count_plays_50` int(11) DEFAULT NULL,
  `count_plays_75` int(11) DEFAULT NULL,
  `count_plays_100` int(11) DEFAULT NULL,
  `count_edit` int(11) DEFAULT NULL,
  `count_viral` int(11) DEFAULT NULL,
  `count_download` int(11) DEFAULT NULL,
  `count_report` int(11) DEFAULT NULL,
  `new_admins` INT(11) DEFAULT NULL,
  `new_videos` INT(11) DEFAULT NULL,
  `deleted_videos` INT(11) DEFAULT NULL,
  `new_images` INT(11) DEFAULT NULL,
  `deleted_images` INT(11) DEFAULT NULL,
  `new_audios` INT(11) DEFAULT NULL,
  `deleted_audios` INT(11) DEFAULT NULL,
  `new_livestreams` INT(11) DEFAULT NULL,
  `deleted_livestreams` INT(11) DEFAULT NULL,
  `new_playlists` INT(11) DEFAULT NULL,
  `deleted_playlists` INT(11) DEFAULT NULL,
  `new_documents` INT(11) DEFAULT NULL,
  `deleted_documents` INT(11) DEFAULT NULL,
  `new_other_entries` INT(11) DEFAULT NULL,
  `deleted_other_entries` INT(11) DEFAULT NULL,
  `flag_active_site` tinyint(4) DEFAULT '0',
  `flag_active_publisher` tinyint(4) DEFAULT '0',
  `count_buf_start` int(11) DEFAULT NULL,
  `count_buf_end` int(11) DEFAULT NULL,
  `count_open_full_screen` int(11) DEFAULT NULL,
  `count_close_full_screen` int(11) DEFAULT NULL,
  `count_replay` int(11) DEFAULT NULL,
  `count_seek` int(11) DEFAULT NULL,
  `count_open_upload` int(11) DEFAULT NULL,
  `count_save_publish` int(11) DEFAULT NULL,
  `count_close_editor` int(11) DEFAULT NULL,
  `count_pre_bumper_played` int(11) DEFAULT NULL,
  `count_post_bumper_played` int(11) DEFAULT NULL,
  `count_bumper_clicked` int(11) DEFAULT NULL,
  `count_preroll_started` int(11) DEFAULT NULL,
  `count_midroll_started` int(11) DEFAULT NULL,
  `count_postroll_started` int(11) DEFAULT NULL,
  `count_overlay_started` int(11) DEFAULT NULL,
  `count_preroll_clicked` int(11) DEFAULT NULL,
  `count_midroll_clicked` int(11) DEFAULT NULL,
  `count_postroll_clicked` int(11) DEFAULT NULL,
  `count_overlay_clicked` int(11) DEFAULT NULL,
  `count_preroll_25` int(11) DEFAULT NULL,
  `count_preroll_50` int(11) DEFAULT NULL,
  `count_preroll_75` int(11) DEFAULT NULL,
  `count_midroll_25` int(11) DEFAULT NULL,
  `count_midroll_50` int(11) DEFAULT NULL,
  `count_midroll_75` int(11) DEFAULT NULL,
  `count_postroll_25` int(11) DEFAULT NULL,
  `count_postroll_50` int(11) DEFAULT NULL,
  `count_postroll_75` int(11) DEFAULT NULL,
  PRIMARY KEY (`partner_id`,`date_id`,`hour_id`),
  KEY (`date_id`,`hour_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8
PARTITION BY RANGE (date_id)
(PARTITION p_201001 VALUES LESS THAN (20100201) ENGINE = INNODB,
 PARTITION p_201002 VALUES LESS THAN (20100301) ENGINE = INNODB,
 PARTITION p_201003 VALUES LESS THAN (20100401) ENGINE = INNODB,
 PARTITION p_201004 VALUES LESS THAN (20100501) ENGINE = INNODB,
 PARTITION p_201005 VALUES LESS THAN (20100601) ENGINE = INNODB,
 PARTITION p_201006 VALUES LESS THAN (20100701) ENGINE = INNODB,
 PARTITION p_201007 VALUES LESS THAN (20100801) ENGINE = INNODB,
 PARTITION p_201008 VALUES LESS THAN (20100901) ENGINE = INNODB,
 PARTITION p_201009 VALUES LESS THAN (20101001) ENGINE = INNODB,
 PARTITION p_201010 VALUES LESS THAN (20101101) ENGINE = INNODB,
 PARTITION p_201011 VALUES LESS THAN (20101201) ENGINE = INNODB);
