SELECT *
FROM kalturadw_ds.cycles
WHERE  (STATUS IN ('GENERATED','PROCESSED','LOADED') AND insert_time < NOW() - INTERVAL 1 DAY)
  OR 
 (STATUS IN ('GENERATING','REGISTERED') AND run_time < NOW() - INTERVAL 1 HOUR)
 OR 
 (STATUS = 'RUNNING' AND run_time < NOW() - INTERVAL 2 HOUR)
 OR 
 (STATUS = 'LOADING' AND run_time < NOW() - INTERVAL 2 HOUR)
 OR 
 (STATUS = 'TRANSFERING' AND transfer_time < NOW() - INTERVAL 2 HOUR)
 OR 
 STATUS NOT IN ('DONE', 'GENERATED', 'GENERATING', 'REGISTERED', 'PROCESSED', 'LOADED', 'RUNNING', 'LOADING','TRANSFERING', 'DELETED', 'SPOOF_CYCLE')


